[build-system]
requires = ["wheel", "setuptools"]
build-backend = "setuptools.build_meta"


[tool.black]
line-length     = 120
target-version  = ["py39"]
include         = ".*pyi?$"

[tool.pyright]
include = ["examples", "tanjun", "noxfile.py"]

reportMissingImports = true
reportMissingTypeStubs = true

pythonVersion = "3.9"
reportIncompatibleMethodOverride = "warning"  # This relies on ordering for key-word only arguments 
                                              # which is more annoying than it's worth
reportUnknownMemberType = "warning"           # This messes with instance checking generic objects
reportUnknownArgumentType = "warning"         # Pretty much the same as reportUnknownMemberType
reportImportCycles = "warning"                # This isn't necessarily an issue if it's type checking only.
[tool.pytest.ini_options]
import-mode = "???"
testpaths = ["tests"]
required_plugins = ["pytest-asyncio"]
